name: Auto-Assign Issues
on:
  issues:
    types: [opened, edited, labeled]
jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
    - name: Check Labels
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.MY_GITHUB_TOKEN }}
        script: |
          const issue = context.payload.issue
          const teamId = "7587515" // Replace with the ID of the team to which you want to assign issues
          const res = await github.teams.listMembersInOrg({
            team_id: teamId,
            role: "member"
          })
          const members = res.data.map(member => member.login)
          const assignee = members[Math.floor(Math.random() * members.length)]
          const params = {
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issue.number,
            assignees: [assignee]
          }
          await github.issues.addAssignees(params)
