name: Issue assignment

on:
  issues:
    types: [opened, edited, labeled]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: 'Auto-assign issue'
        uses: pozil/auto-assign-issue@v1
        with:
          repo-token: ${{ secrets.MY_ASSIGNMENT_TOKEN }}
          teams: dank-style
          numOfAssignee: 1
          allowSelfAssign: false
