name: Auto-Assign Issues
on:
  issues:
    types: [opened, edited, labeled]
jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
    - name: Get team members
      id: team_members
      uses: peter-evans/get-team-members@v1
      with:
        team-id: 7579007 # Replace with your team ID
        role: member
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Assign issue
      uses: peter-evans/assignee@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        assignees: ${{ steps.team_members.outputs.members[steps.team_members.outputs.count] }}
