name: Auto-Backmerge PR

on:
  push:
    branches:
      - main

jobs:
  create-backmerge-pr:
    name: Create Backmerge PR
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: devops-infra/action-pull-request@v0.5.3
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          source_branch: main
          target_branch: patch
          title: 'Backmerge Main -> Patch'
