name: Auto-Backmerge PR

on:
  push:
    branches:
      - main

jobs:
  create-backmerge-pr:
    name: Create Backmerge PR
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Create Backmerge PR
        run: |
          hub pull-request -h main -b patch -m "BackMerge: Main -> Patch"
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
